services:
  app:
    image: ilyaguev/docker-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
#    environment:
#      DATABASE_NAME: ${DATABASE_NAME}
#      DATABASE_USERNAME: ${DATABASE_USERNAME}
#      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
#      DATABASE_HOST: ${DATABASE_HOST}
#      DATABASE_PORT: ${DATABASE_PORT}
    command: >
      sh -c "make prepare-env && make test"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
        POSTGRES_DB: ${DATABASE_NAME}
        POSTGRES_USER: ${DATABASE_USERNAME}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
        - "${DATABASE_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
